routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\SigninController;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/index', 'SigninController@first');
Route::get('/login', 'SigninController@login');
Route::post('/welcome', 'SigninController@welcome');

Route::get('/table', 'TableController@table');
Route::get('/datatable', 'TableController@datatable');

Route::resource('/cast', 'CastController');

app/Cast.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cast extends Model
{
    protected $guarded = ['id'];
}

app/Http/Controllers/CastController.php
<?php

namespace App\Http\Controllers;

use App\Cast;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CastController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $casts = Cast::all();
        return view('cast.index', compact('casts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cast.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required',
            'umur' => 'required|integer',
            'bio'   => 'required'
        ]);
        DB::table('casts')->insert([
            'nama' => $request->nama,
            'umur' => $request->umur,
            'bio'  => $request->bio,
        ]);

        return redirect()->route('cast.index')->with('success','Data berhasil ditambahkan');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Cast  $cast
     * @return \Illuminate\Http\Response
     */
    public function show(Cast $cast)
    {
        return view('cast.show', compact('cast'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Cast  $cast
     * @return \Illuminate\Http\Response
     */
    public function edit(Cast $cast)
    {
        return view('cast.edit', compact('cast'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Cast  $cast
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Cast $cast)
    {
        $request->validate([
            'nama' => 'required',
            'umur' => 'required|integer',
            'bio'   => 'required'
        ]);
        $query = DB::table('casts')->where('id', $cast->id)->update([
            'nama' => $request->nama,
            'umur' => $request->umur,
            'bio'  => $request->bio,
        ]);

        return redirect()->route('cast.show', $cast)->with('success', 'Data berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Cast  $cast
     * @return \Illuminate\Http\Response
     */
    public function destroy(Cast $cast)
    {
        $query = DB::table('casts')->where('id', $cast->id)->delete();

        return redirect()->route('cast.index')->with('success', 'Data berhasil dihapus');
    }
}

resources/views/cast/create.blade.php
@extends('adminlte::page')

@section('title', 'Create Cast')



@section('content')
    <br>
    @if ($errors->any())
            @foreach ($errors->all() as $error)
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <strong>Gagal!</strong> {{ $error }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endforeach
    @endif
    @if ($success = Session::get('success'))
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Selamat!</strong> {{ $success }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif
    <br>
    <div class="section">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title mb-3">Input Data Cast</h5>
                <form action="{{ route('cast.store') }}" method="POST">
                    @csrf
                    <div class="input-group mb-3 mt-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroup-sizing-default">Nama Cast</span>
                        </div>
                        <input type="text" class="form-control" aria-label="Sizing example input"
                            aria-describedby="inputGroup-sizing-default" name="nama" required value="{{ old('nama') }}">
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroup-sizing-default">Umur Cast</span>
                        </div>
                        <input type="text" class="form-control" aria-label="Sizing example input"
                            aria-describedby="inputGroup-sizing-default" name="umur" required value="{{ old('umur') }}">
                    </div>
                    <div class="form-group mb-3">
                        <label for="exampleFormControlTextarea1">Biografi Cast</label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="bio"
                            required>{{ old('bio') }}</textarea>
                    </div>
                    <button class="btn btn-primary" type="submit">Simpan</button>
                </form>
            </div>
        </div>
    </div>
@stop

resources/views/cast/edit.blade.php
@extends('adminlte::page')

@section('title', 'Create Cast')



@section('content')
    <br>
    @if ($errors->any())
            @foreach ($errors->all() as $error)
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <strong>Gagal!</strong> {{ $error }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endforeach
    @endif
    @if ($success = Session::get('success'))
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Selamat!</strong> {{ $success }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif
    <br>
    <div class="section">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title mb-3">Edit Data Cast</h5>
                <form action="{{ route('cast.update', $cast) }}" method="POST">
                    @method('PATCH')
                    @csrf
                    <div class="input-group mb-3 mt-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroup-sizing-default">Nama Cast</span>
                        </div>
                        <input type="text" class="form-control" aria-label="Sizing example input"
                            aria-describedby="inputGroup-sizing-default" name="nama" required value="{{ $cast->nama }}">
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroup-sizing-default">Umur Cast</span>
                        </div>
                        <input type="text" class="form-control" aria-label="Sizing example input"
                            aria-describedby="inputGroup-sizing-default" name="umur" required value="{{ $cast->umur }}">
                    </div>
                    <div class="form-group mb-3">
                        <label for="exampleFormControlTextarea1">Biografi Cast</label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="bio"
                            required>{{ $cast->bio }}</textarea>
                    </div>
                    <button class="btn btn-primary" type="submit">Update</button>
                </form>
            </div>
        </div>
    </div>
@stop

resources/views/cast/index.blade.php
@extends('adminlte::page')

@section('title', 'Cast')

{{-- @section('content_header')
    <h1>Data Cast</h1>
@stop --}}

@section('content')
    <br>
    @if ($errors->any())
        <div class="row">
            @foreach ($errors->all() as $error)
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <strong>Gagal!</strong> {{ $error }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endforeach
        </div>
    @endif
    @if ($success = Session::get('success'))
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Selamat!</strong> {{ $success }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif
    <br>
    <div class="section">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Data Cast</h5>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Nama</th>
                            <th scope="col">Umur</th>
                            <th scope="col">Bio</th>
                            <th scope="col">Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($casts as $cast)
                            <tr>
                                <th scope="row">{{ $loop->iteration }}</th>
                                <td>{{ $cast->nama }}</td>
                                <td>{{ $cast->umur }}</td>
                                <td>{{ $cast->bio }}</td>
                                <td>
                                    <form action="{{ route('cast.destroy', $cast) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <div class="btn-group">
                                            <a href="{{ route('cast.show', $cast) }}" class="btn btn-success">Detail</a>
                                            <a class="btn btn-secondary" href="{{ route('cast.edit', $cast) }}">Edit</a>
                                            <button type="submit" class="btn btn-danger">Hapus</button>
                                        </div>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                <a href="{{ route('cast.create') }}" class="btn btn-outline-success float-right">Buat Baru</a>
            </div>
        </div>
    </div>
@stop

resources/views/cast/show.blade.php
@extends('adminlte::page')

@section('title', 'Detail Cast')



@section('content')
    <br>
    @if ($errors->any())
        @foreach ($errors->all() as $error)
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>Gagal!</strong> {{ $error }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endforeach
    @endif
    @if ($success = Session::get('success'))
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Selamat!</strong> {{ $success }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif
    <br>
    <div class="section">
        <div class="card">
            <div class="card-header">
                <h5>Detail Data Cast</h5>
            </div>
            <div class="card-body">

                <br>
                <br>
                <div>
                    <h6 class="text-bold">Nama</h6>
                    <p>{{ $cast->nama }}</p>
                    <h6 class="text-bold">Umur</h6>
                    <p>{{ $cast->umur }}</p>
                    <h6 class="text-bold">Biografi</h6>
                    <p>{{ $cast->bio }}</p>
                </div>
            </div>
            <div class="card-footer">
                <form action="{{ route('cast.destroy', $cast) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <div class="btn-group">
                        <a class="btn btn-secondary" href="{{ route('cast.edit', $cast) }}">Edit</a>
                        <button type="submit" class="btn btn-danger">Hapus data</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@stop